import React from 'react'
import { Link } from 'react-router-dom'

const TermsAndConditions: React.FC = () => {
  return (
    <div className="min-h-screen flex flex-col bg-offWhite text-black">
        <main className="flex-grow mt-20 py-10 px-20">
            <h1 className="text-2xl mb-2 font-bold">TERMS AND CONDITIONS</h1>
            <p className="mb-2">Last revised on April 10, 2025</p>
            <h6 className="font-bold mb-2">Welcome to Blind Date, operated by Blind Date Enterprises, Inc. ("us," "we," the "Company" or "Blind Date").</h6>
            <p className="mb-2"><span className="font-bold">California subscribers:</span> You may cancel your subscription at any time before midnight of the third business day after you signed up for it, with no penalty or obligation. If you have subscribed using your Apple ID, Apple manages refunds, not Blind Date. Please go to <Link className="text-blue-600 border-b-2" to='javascript:void(0)' onClick={() => window.location.href = 'https://getsupport.apple.com'}>https://getsupport.apple.com</Link> if you need to request a refund. If you used your Google Play Store account or downloaded Blind Date online, you may contact <Link className="text-blue-600 border-b-2" to='javascript:void(0)' onClick={() => window.location.href = 'mailto:help@blinddate.world'}>help@blinddate.world</Link>.</p>
            <h6 className="mb-2 text-lg font-bold">1. By using our Services, you agree to the Terms of Use Agreement</h6>
            <p className="mb-2">To access the Blind Date website and its services, you must first register for a Blind Date account or utilize all Blind Date services through a mobile device, mobile application, or computer (the "Service"). By registering on our Service, you agree to be bound by these Terms and Conditions:</p>
            <ul className="mb-2">
                <li className="mb-2 list-disc ml-10 pl-5">These Terms of Service</li>
                <li className="mb-2 list-disc ml-10 pl-5">Blind Date's <Link className="border-b-2 text-blue-600" to={'/legal/privacy_policy'}>Privacy Policy</Link> and <Link className="border-b-2 text-blue-600" to={'/legal/safety_tips'}>Safety Tips</Link>, each of which is incorporated by reference into this Agreement.</li>
                <li className="mb-2 list-disc ml-10 pl-5">If you have purchased or will purchase additional features, goods, or services from us on the Service, we will disclose any special terms to you (collectively, this "Agreement")</li>
            </ul>
            <p className="mb-2">In any case that you do not acknowledge and consent to being bound by the terms mentioned on this Agreement (other than the limited one-time opt-out suitable for particular users discussed in Section 13), then you should not use the Service.</p>
            <p className="mb-2">We may sometimes update this Agreement and the Service as we continuously develop our product over time. However, most of these modifications will most likely be legal in nature. We make changes for various reasons, including but not limited to reflect changes in or requirements of the law, new features, or changes in business practices.</p>
            <p className="mb-2">The current version of this Agreement will be published on "Service" under Settings and the <Link className="border-b-2 text-blue-600" to={'/'}>Blind Date website</Link>. Regularly review this Terms of Use page for the latest updates on our terms and conditions, as the newest version will apply to all users. If the modifications on our terms may affect your rights or commitments, we will make sure to advise our users in advance by suitable means, which may come in the form of notifications through the Service or via email. If you continue to use Blind Date's Service after changes are implemented, then it means that you give your consent to the revised Agreement. This also expresses your approval that this Agreement shall supersede any prior agreements (except as expressly stated herein) and shall govern your entire relationship with Blind Date, including, but not limited to, events, arrangements, and conduct preceding your acceptance of this Agreement.</p>
            <h6 className="mb-2 text-lg font-bold">2. Eligibility Requirements</h6>
            <p className="mb-2">You must be at least 18 years of old to be eligible to create an account on Blind Date and use the Service. By creating an account and using our Service, you now represent and certify that:</p>
            <ul className="mb-2">
                <li className="mb-2 list-disc ml-10 pl-5">You are qualified to create a binding and legal contract with Blind Date,</li>
                <li className="mb-2 list-disc ml-10 pl-5">You are not someone who is barred from using the Service under the regulations of the United States or any other jurisdiction–indicating that you are not in the U.S. Treasury Department's list of Specially Designated Nationals or are facing any other similar prohibition,</li>
                <li className="mb-2 list-disc ml-10 pl-5">You will adhere to the term of this Agreement and all relevant local, state, international and national laws, rules, and regulations, and</li>
                <li className="mb-2 list-disc ml-10 pl-5">You have never been sentenced to or have pled no contest to a felony, a sex crime, or any offense involving violence, and you are not required to report as a sex criminal with any state, federal, or local sex offender registry.</li>
            </ul>
            <h6 className="mb-2 text-lg font-bold">3. Your Account</h6>
            <p className="mb-2">To utilize Blind Date, you should sign in to your Blind Date account with either your Google or Apple account. You are liable for keeping the confidentiality of your own login credentials that you use to sign up for Blind Date, and you are exclusively accountable for all actions that transpire under those credentials. Blind Date is not answerable for a lack of confidentiality on the user's part. However, if you presume that somebody may have gained unauthorized access to your account, please directly contact us at <Link className="text-blue-600 border-b-2" to='javascript:void(0)' onClick={() => window.location.href = 'mailto:help@blinddate.world'}>help@blinddate.world</Link></p>
            <h6 className="mb-2 text-lg font-bold">4. Modifying the Service and Termination</h6>
            <p className="mb-2">Blind Date's goal is to continuously improve the Service and its functionality in order to keep the Service appealing and useful to all of our users. This means that we may add new product features or enhancements or remove some features as we see fit, and if these measures do not directly affect any of your rights or obligations, we may not notify you before taking such actions. We may even discontinue the Service entirely, in which case we will notify you in advance unless there are compelling reasons, such as safety or security concerns, that prevent us from doing it.</p>
            <p className="mb-2">You may cancel your account at any time for any reason by going to the Service's "Settings" and following the steps; however, if you used a third-party payment method, you may need to manage in-app purchases through that payment platform's account (e.g., iTunes, Google Play) in order not to be charged again.</p>
            <p className="mb-2">Your account with Blind Date may be closed at any time without notice if it believes you have violated this Agreement. If your Blind Date account is terminated, you will not be eligible for any refund for purchases. This Agreement will come to an end after your account has been closed, except for the following sections that will continue to apply to you and Blind Date: Section 4, Section 5, and Sections 11 through 17.</p>
            <h6 className="mb-2 text-lg font-bold">5. Safety Provisions; Your Interactions with Others</h6>
            <p className="mb-2">Blind Date tries to foster a safe user experience through features like warnings, but it is not responsible for any user's behavior on or off the Service. You, as the User, agree to exercise caution in all interactions with other users, particularly if you choose to communicate outside of the Service or meet in person. In addition, before using the Service, you agree to review and obey Blind Date's Safety Tips. You also comply that you will not share your financial information (such as credit card or bank account numbers) with other users, nor will you wire or otherwise pay money to them.</p>
            <p className="mb-2">BLIND DATE DOES NOT PERFORM CRIMINAL BACKGROUND CHECKS ON ITS USERS OR OTHERWISE INQUIRE INTO THE BACKGROUND OF ITS USERS, AND BLIND DATE MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF USERS. THUS, YOU ARE SOLELY RESPONSIBLE FOR YOUR DEALINGS AND LEVEL OF INTERACTIONS WITH OTHER USERS. BLIND DATE ALSO RESERVES THE RIGHT TO CONDUCT ANY CRIMINAL BACKGROUND CHECK OR OTHER SCREENINGS (INCLUDING SEX OFFENDER REGISTRIES) AT ANY TIME USING AVAILABLE PUBLIC RECORDS, AND YOU AGREE THAT BLIND DATE MAY DO SO.</p>
            <h6 className="mb-2 text-lg font-bold">6. Rights That Blind Date Grants You</h6>
            <p className="mb-2">Blind Date grants you a personal, royalty-free, non-assignable, nonexclusive, revocable, worldwide, and non-sublicensable license to use and operate our Service. This license is solely for the purpose of enabling you to use and enjoy the benefits of the Service as intended by Blind Date and as authorized by this Agreement. As a result, you agree not to:</p>
            <ul className="mb-2">
                <li className="mb-2 list-disc ml-10 pl-5">Without our explicit and written consent, use the Service or any content provided in the Service for any commercial purposes.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Without Blind Date's prior written consent, you may not copy, alter, distribute, construct any altered pieces from, use, or duplicate in any way any copyrighted material, images, trademarks, trade names, service marks, or other intellectual property, content, or proprietary information accessible through the Service.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Represent or imply that Blind Date agrees with whatever assertions you make.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Use any technology, such as a robot, bot, spider, crawler, scraper, site search/retrieval application, a proxy, or any other manual or automated device, method, or process, to access, retrieve, index, "data mine," or otherwise reproduce or circumvent the Service's navigational structure or presentation.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Use Blind Date's Service in any way that could interfere with, disrupt, or harm the Service or the systems or networks that are connected to the Service.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Upload viruses or other malicious programming, or otherwise jeopardize the Service's security.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Forge headers or otherwise modify identifiers to conceal the origin of any data transmitted to or through the Service.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Without Blind Date's prior written permission, you may not "frame" or "mirror" any portion of the Service.</li>
                <li className="mb-2 list-disc ml-10 pl-5">The implementation of meta tags, code, or other devices containing any reference to Blind Date or the Service (or any of Blind Date's trademarks, trade names, service marks, logos, or slogans) to send any person to any other website for any purpose.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Modify, adapt, sublicense, translate, sell, reverse engineer, decrypt, decompile, or otherwise disassemble any part of the Service, or allow others to do so.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Without our written permission, you are not permitted to use or develop any third-party apps that interact with the Service or other users' content or data.</li>
                <li className="mb-2 list-disc ml-10 pl-5">You may not use, access, or publish the Blind Date application programming interface without our written permission.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Look into, probe, or test the vulnerability of our Service or any system or network.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Encourage or promote any activity that is contrary to the terms of this Agreement.</li>
            </ul>
            <p className="mb-2">In reaction to illegal and/or unauthorized uses of the Service in violation of this Agreement, Blind Date may conduct an investigation and take any applicable legal action, including the cancellation of your account.</p>
            <p className="mb-2">Any program that we offer you with may download and install upgrades, updates, or other new features automatically. You may be able to switch these automatic downloads on and off via your device's settings.</p>
            <h6 className="mb-2 text-lg font-bold">7. Rights You Grant Blind Date</h6>
            <p className="mb-2">By creating an account, you grant Blind Date the right and license to host, store, use, copy, display, reproduce, adapt, edit, publish, modify, and distribute the information you authorize us to access from Google, or Apple, as well as any information you post, upload, display, or otherwise make available (collectively, "post") on the Service or transmit to other users (collectively, "post") (collectively, "Content").</p>
            <p className="mb-2">Blind Date's license to your Content is non-exclusive, except for derivative works created via the use of the Service, in which case Blind Date's license is exclusive. For example, Blind Date would have an exclusive license to screenshots of the Service that include your Content. Furthermore, in order for Blind Date to restrict the use of your Content outside of the Service, you allow Blind Date to intervene on your behalf in cases of infringement involving your Content removed from the Service by other users or third parties. This clearly includes the authority, but not the responsibility, to issue warnings under 17 U.S.C. 512(c)(3) (i.e., DMCA Takedown Notices) on your behalf if third parties take and utilize your Content outside of the Service.</p>
            <p className="mb-2">Our license to your Content is subject to your rights under applicable law (for example, laws governing personal data protection if any Content contains personal information as defined by those laws) and is limited to operating, developing, providing, and improving the Service, as well as researching and developing new ones.</p>
            <p className="mb-2">You accept that any Content you post or permit us to post on the Service can be viewed by anyone who is vis or participates in the Service (such as individuals who may receive shared Content from other Blind Date users).</p>
            <p className="mb-2">You agree that all information that you submit upon creation of your account, including information submitted from your Facebook account, is accurate and truthful. You have the right to post the Content on the Service and grant the license to Blind Date above.</p>
            <p className="mb-2">You understand and agree that Blind Date may monitor and review any Content you post to the Service. We may delete any Content, in whole or in part, that we deem violates this Agreement or may harm the reputation of the Service.</p>
            <p className="mb-2">You agree to be respectful and kind when talking with our support team representatives as we endeavor to assist you with your issue or concern. We reserve the right to instantly delete your account if we believe your behavior towards any of our support team members or other employees is threatening or insulting at any time.</p>
            <p className="mb-2">You agree that by submitting comments or feedback about our Service to Blind Date, you accept that Blind Date may use and disseminate that feedback for any purpose without compensating you.</p>
            <p className="mb-2">You agree that Blind Date may access, preserve, and disclose your account information and Content if required by law or in the good faith belief that such access, preservation, or disclosure is reasonably necessary, such as to: (i) comply with legal process; (ii) enforce this Agreement; (iii) respond to claims that any Content violates the rights of third parties; (iv) respond to your customer service requests; or (v) protect the rights, the property, or personal safety of others.</p>
            <h6 className="mb-2 text-lg font-bold">8. Community Rules</h6>
            <p className="mb-2">You are agreeing that by using the Service, you will therefore not:</p>
            <ul className="mb-2">
                <li className="mb-2 list-disc ml-10 pl-5">Use the Service for any illicit or illegal activity or activity expressly or tacitly forbidden by this Agreement.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Utilize the Service for any nefarious purposes.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Make use of the Service to criticize or harm Blind Date.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Violate our Community Guidelines, which may be updated from time to time.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Other users should not be spammed, solicited for money, or defrauded.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Impersonate another person or entity, or post photographs of another person without their consent.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Any individual may be bullied, "stalked," intimidated, assaulted, harassed, mistreated, or defamed.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Post any Content that hampers or violates the rights of others, including rights of publicity, privacy, copyright, trademark, or any other intellectual property or contractual right.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Publish any Content that is hate speech, threatening, sexually explicit, or pornographic; incites violence, or contains nudity, graphic or gratuitous violence.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Publish any Content that encourages racism, bigotry, hatred, or physical damage to any group or individual.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Solicit the passwords or other personal identifying information from other users for commercial or illicit purposes, or broadcast another person's personal information without his or her permission.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Use another user's account, share an account with another user, or have multiple accounts</li>
                <li className="mb-2 list-disc ml-10 pl-5">If we have already terminated your account, you may not create a new account without our permission.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Post any Content that violates or poses infringement on the rights of others, including rights for publicity, privacy, copyright, trademark, or any of other intellectual property or contractual right.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Publish any Content that is hate speech, threatening, sexually explicit, or pornographic; incites violence, or contains nudity, graphic or gratuitous violence.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Any content that promotes racism, bigotry, hatred, or physical harm to any group or individual should be removed.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Solicit passwords or personal identifying information from other users for commercial or illegal purposes, or broadcast another person's personal information without permission.</li>
                <p className="mb-2">If we find you in violation of this Agreement, misusing the Service, or acting in a way that Blind Date considers inappropriate or unlawful, including actions or communications that occur on or off the Service, we reserve the right to investigate and/or terminate your account without a refund of any purchases.</p>
                <h6 className="mb-2 text-lg font-bold">9. Other Users' Content</h6>
                <p className="mb-2">While Blind Date maintains the right to review and remove Content that violates this Agreement, such Content is solely the responsibility of the user who uploads it, and Blind Date cannot guarantee that all Content will comply with this Agreement.</p>
                <p className="mb-2">If you come across any Content on the Service that violates this Agreement, please report it through the Service and we will address it appropriately.</p>
            </ul>
            <h6 className="mb-2 text-lg font-bold">10. Purchases</h6>
            <p className="mb-2">Blind Date may, from time to time, make products and services available for purchase ("in-app purchases") via iTunes, Google Play, mobile billing, Blind Date direct billing, or other payment methods permitted by Blind Date.</p>
            <p className="mb-2">If you choose to make an in-app purchase, you will be prompted to confirm your purchase with the applicable payment provider, and your method of payment (whether it is your card or a third-party account like Google Play or iTunes) (the user's "Payment Method") will be charged at the prices displayed to you for the Service (s) you've chosen, plus any sales or similar taxes that may be imposed on your payments, and you authorize Blind Date or the third-party account, as applicable, to charge you.</p>
            <p className="mb-2 font-bold">Auto-Renewal</p>
            <p className="mb-2">If you purchase an automatic recurring periodic membership, your Payment Method will be charged until you cancel the subscription. Following your original subscription commitment time, and again following any future subscription period, your subscription will automatically renew for an extra similar period at the price you agreed to when subscribing.</p>
            <p className="mb-2">If you do not want your subscription to automatically renew, or if you should want to change or terminate your Blind Date subscription, you need to log in to your third-party account (or Account Settings on Blind Date) and follow the cancellation instructions, even if you have previously deleted your account with us or the Blind Date application from your device.</p>
            <p className="mb-2">Deleting your Blind Date account or removing the Blind Date app from your device does not cancel your subscription; Blind Date will keep all funds charged to your Payment Method until you cancel your subscription on Blind Date or the third-party account, as applicable. If you cancel your membership, you may continue to use it until the end of your then-current subscription period, but it will not be renewed after that term expires.</p>
            <p className="mb-2 font-bold">Additional Terms that apply if you pay Blind Date directly with your Payment Method</p>
            <p className="mb-2">If you pay Blind Date directly, Blind Date has the right to fix any billing errors or inaccuracies it makes, even if payment has already been requested or received. If you initiate a chargeback or otherwise reverse a payment made with your Payment Method, Blind Date may, in its sole discretion, deactivate your account immediately.</p>
            <p className="mb-2">If your payment is not successfully settled, whether due to expiration, insufficient funds, or other reasons, and you do not edit your Payment Method information or cancel your subscription, you remain liable for any uncollected amounts and authorize us to continue billing the Payment Method, as it may be updated.</p>
            <p className="mb-2">If payment is not successfully settled, due to expiration, insufficient funds, or otherwise, and you do not edit your Payment Method information or cancel your subscription, you remain responsible for any uncollected amounts and authorize us to continue billing the Payment Method, as it may be updated.</p>
            <p className="mb-2">This may cause a shift in your payment billing dates. Furthermore, you permit us to receive updated or replacement expiration dates and card numbers for your credit or debit card from the issuer of your credit or debit card. The conditions of your payment will be decided by agreements between you and the banking institution, credit card issuer, or another supplier of your preferred Payment Method. If you live outside of the Americas, you agree to pay Blind Date using Blind Date's chosen payment partner.</p>
            <p className="mb-2 font-bold">Refunds</p>
            <p className="mb-2">In general, all costs for purchases are nonrefundable, and no refunds or credits are given for partially utilized periods. We may make an exception if a refund for a subscription offering is requested within fourteen days of the transaction date, or if your jurisdiction's laws allow for returns.</p>
            <p className="mb-2">For subscribers residing in Arizona, California, Connecticut, Illinois, Iowa, Minnesota, New York, North Carolina, Ohio, and Wisconsin, the terms below apply:</p>
            <p className="mb-2">Without penalty or obligation, you may cancel your membership at any time before midnight on the third business day after the day you registered. If you die before the end of your subscription period, your account is entitled to a refund of the portion of any subscription payment you made that is allocable to the time following your death.</p>
            <p className="mb-2">If you become disabled (unable to use Blind Date's services) before the end of your subscription period, you are entitled to a refund of that portion of any payment you made for your subscription that is allocable to the period following your disability by providing the company notice in the same manner as you request a refund as described below.</p>
            <p className="mb-2">To request a refund:</p>
            <p className="mb-2">Refunds are handled by Apple, not Blind Date, if you subscribed using your Apple ID. To seek a refund, go to iTunes, sign in with your Apple ID, pick "Purchase history," identify the transaction, and click "Report Problem."</p>
            <p className="mb-2">You may also send an email to: <Link className="text-blue-600 border-b-2" to='javascript:void(0)' onClick={() => window.location.href = 'https://getsupport.apple.com'}>https://getsupport.apple.com</Link>.</p>
            <p className="mb-2">If you have subscribed using your Google Play Store account or directly through Blind Date, please contact customer service             <Link className="text-blue-600 border-b-2" to='javascript:void(0)' onClick={() => window.location.href = 'mailto:help@blinddate.world'}>help@blinddate.world</Link> with your order number for the Google Play Store (by checking in to Google Wallet).</p>
            <p className="mb-2">You may also send an email with a signed and dated notification declaring that you, the buyer, are canceling this agreement or anything to that effect. Along with your order number, please give the email address or phone number linked with your account. This message should be sent to the following address: <Link className="text-blue-600 border-b-2" to='javascript:void(0)' onClick={() => window.location.href = 'mailto:help@blinddate.world'}>help@blinddate.world</Link>.</p>
            <h6 className="mb-2 text-lg font-bold">11. Disclaimers</h6>
            <p className="mb-2">BLIND DATE PROVIDES THE SERVICE ON AN "AS IS" AND "AS AVAILABLE" BASIS AND TO THE EXTENT PERMITTED BY APPLICABLE LAW, GRANTS WITH NO WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE CONCERNING THE SERVICE (INCLUDING ALL THE CONTENT CONTAINED THEREIN), INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF SATISFACTORY QUALITY, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. BLIND DATE DOES NOT REPRESENT OR WARRANT THAT A) THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE, B) ANY DEFECTS OR ERRORS IN THE SERVICE WILL BE CORRECTED, OR C) THAT ANY CONTENT OR INFORMATION YOU OBTAIN ON OR THROUGH THE SERVICE WILL BE ACCURATE.</p>
            <p className="mb-2">BLIND DATE ASSUMES NO LIABILITY FOR ANY CONTENT POSTED, SENT, OR RECEIVED THROUGH THE SERVICE BY YOU OR ANY OTHER USER OR THIRD PARTY. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS ACCESSED AT YOUR OWN DISCRETION AND RISK.</p>
            <p className="mb-2">BLIND DATE DISCLAIMS AND TAKES NO RESPONSIBILITY FOR ANY CONDUCT OF YOU OR ANY OTHER USER, ON OR OFF THE SERVICE.</p>
            <h6 className="mb-2 text-lg font-bold">12. Limitation of Liability</h6>
            <p className="mb-2">TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL BLIND DATE, ITS AFFILIATES, EMPLOYEES, LICENSORS OR SERVICE PROVIDERS BE LIABLE FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, PUNITIVE, OR ENHANCED DAMAGES, INCLUDING, WITHOUT LIMITATION, LOSS OF PROFITS, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM: (I) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE; (II) THE CONDUCT OR CONTENT OF OTHER USERS OR THIRD-PARTIES ON, THROUGH OR FOLLOWING USE OF THE SERVICE; OR (III) UNAUTHORIZED ACCESS, USE OR ALTERATION OF YOUR CONTENT, EVEN IF BLIND DATE HAS BEEN ADVISED AT ANY TIME OF THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING THE FOREGOING, IN NO EVENT SHALL BLIND DATE'S AGGREGATE LIABILITY TO YOU FOR ANY AND ALL CLAIMS ARISING OUT OF OR RELATING TO THE SERVICE OR THIS AGREEMENT EXCEED THE AMOUNT PAID, IF ANY, BY YOU TO BLIND DATE DURING THE TWENTY-FOUR (24) MONTH PERIOD IMMEDIATELY PRECEDING THE DATE THAT YOU FIRST FILE A LAWSUIT, ARBITRATION OR ANY OTHER LEGAL PROCEEDING AGAINST BLIND DATE, WHETHER IN LAW OR EQUITY, IN ANY TRIBUNAL.</p>
            <p className="mb-2">THE DAMAGES LIMITATION OUTLINE IN THE IMMEDIATELY PRECEDING SENTENCE APPLIES (I) REGARDLESS OF THE GROUND UPON WHICH LIABILITY IS BASED (WHETHER DEFAULT, CONTRACT, TORT, STATUTE, OR OTHERWISE), (II) IRRESPECTIVE OF THE TYPE OF BREACH OF OBLIGATIONS, AND (III) WITH RESPECT TO ALL EVENTS, THE SERVICE, AND THIS AGREEMENT.</p>
            <p className="mb-2">THE LIMITATION OF LIABILITY PROVISIONS OUTLINED IN THIS SECTION 12 SHALL APPLY EVEN IF YOUR REMEDIES UNDER THIS AGREEMENT FAIL CONCERNING THEIR ESSENTIAL PURPOSE.</p>
            <p className="mb-2">SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO SOME OR ALL OF THE EXCLUSIONS AND LIMITATIONS IN THIS SECTION MAY NOT APPLY TO YOU.</p>
            <h6 className="mb-2 text-lg font-bold">13. Retroactive and Prospective Arbitration, Class-Action Waiver, and Jury Waiver</h6>
            <p className="mb-2">Except where prohibited by applicable law:</p>
            <ul className="mb-2">
                <li className="mb-2 list-disc ml-10 pl-5">BINDING ARBITRATION administered by the American Arbitration Association under the Consumer Arbitration Rules shall be the exclusive means of resolving any dispute or claim arising out of or relating to this Agreement (including any alleged breach thereof) or the Service, regardless of the date of accrual and including past, pending, and future claims. The one exception to the arbitration exclusivity is that you have the right to file an individual claim against Blind Date in a small claims court of competent jurisdiction in the county in where you reside or in the state of Colorado. Unless either you or Blind Date elects to seek the right to an oral hearing before the Arbitrator, such arbitration shall be conducted solely through written submissions. However, whether you select arbitration or small-claims court, you agree that you will not initiate, maintain, or participate in any class action, class arbitration, or other representative action or process against Blind Date under any circumstances.</li>
                <li className="mb-2 list-disc ml-10 pl-5">By accepting this Agreement, you agree to the Arbitration Agreement in this Section 13. In doing so, BOTH YOU AND BLIND DATE GIVE UP THE RIGHT TO GO TO COURT to assert or defend any claims between you and Blind Date (except for matters that may be properly taken to a small claims court and are within such court's jurisdiction). YOU ALSO GIVE UP YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION OR OTHER CLASS PROCEEDING, including, without limitation, any past, pending, or future class actions.</li>
                <li className="mb-2 list-disc ml-10 pl-5">If you assert a Claim against Blind Date outside of small claims court, your rights will be determined by a NEUTRAL ARBITRATOR, NOT A JUDGE OR JURY, and the arbitrator shall determine all claims and all issues regarding the arbitrability of the dispute. The same applies to Blind Date. Both you and Blind Date are entitled to a fair hearing before the arbitrator. The arbitrator can generally grant a court's relief, but you should note that arbitration proceedings are usually simpler and more streamlined than trials and other judicial proceedings. Decisions by the arbitrator are enforceable in court and may be overturned by a court only for very limited reasons. For details on the arbitration process, see our Arbitration Procedures.</li>
                <li className="mb-2 list-disc ml-10 pl-5">Sections 14’s and 15’s Jurisdiction and Venue requirements are incorporated and apply to this Arbitration Agreement. Here are some essential points to keep in mind as you decide whether or not to accept this Arbitration Agreement.</li>
                <ul className="mb-2">
                    <li className="mb-2 list-disc ml-20 pl-5">Arbitration is a private dispute settlement method that does not use the civil courts, a civil judge, or a jury. Instead, the parties' dispute is resolved by a private arbitrator chosen by the parties following the American Arbitration Association's Consumer Arbitration Rules. Accepting arbitration will only influence where those claims can be filed and how they are resolved.</li>
                    <li className="mb-2 list-disc ml-20 pl-5">Arbitration does not limit or alter any legal claims you may have against Blind Date as an individual.</li>
                    <li className="mb-2 list-disc ml-20 pl-5">Arbitration is typically thought to be a faster method of resolving disputes than the legal system, however this is not always the case. Based on the circumstances, the Arbitrator will normally assess whether Blind Date or you will be compelled to pay or split the cost of any arbitration with Blind Date.</li>
                    <li className="mb-2 list-disc ml-20 pl-5">IMPORTANT: THERE ARE NOW, AND MAY BE IN THE FUTURE, LAWSUITS AGAINST BLIND DATE ALLEGING CLASS AND/OR REPRESENTATIVE CLAIMS ON YOUR BEHALF, WHICH IF SUCCESSFUL, COULD POTENTIALLY RESULT IN SOME MONETARY OR OTHER RECOVERY TO YOU, IF YOU CHOOSE TO OPT-OUT OF THE RETROACTIVE APPLICATION OF THIS ARBITRATION AGREEMENT. THE EXISTENCE OF SUCH CLASS AND/OR REPRESENTATIVE LAWSUITS, HOWEVER, DOES NOT IMPLY THAT SUCH LAWSUITS WILL ULTIMATELY SUCCEED, OR THAT YOU WILL BE ENTITLED TO ANY RECOVERY EVEN IF SUCCESSFUL.</li>
                    <li className="mb-2 list-disc ml-20 pl-5">You will be barred from bringing any class or representative action against Blind Date unless you timely opt-out of the retroactive application of this Arbitration Agreement, and you will also be barred from participating in any recovery resulting from any class or representative action brought against Blind Date, unless an arbitration agreement already binds you and class action waiver previously agreed to with Blind Date.</li>
                    <li className="mb-2 list-disc ml-20 pl-5">According to AAA Consumer Arbitration Rules Rule R-9, either party to an arbitration involving a claim within the jurisdiction of a small claims court may elect to have the matter handled by the small claims court rather than the arbitration. For more information, please see Rule R-9. Nothing in this Agreement, including the consumer's (but not Blind Date's) ability to file a dispute immediately in small claims court rather than commencing arbitration, should be interpreted as contradicting any party's right to invoke Rule R-9 once an arbitration has been commenced.</li>
                </ul>
                <li className="mb-2 list-disc ml-10 pl-5">WHETHER OR NOT TO AGREE TO THIS ARBITRATION AGREEMENT IS AN IMPORTANT DECISION, AND YOU SHOULD TAKE CARE TO CONDUCT FURTHER RESEARCH AND CONSULT WITH OTHERS — INCLUDING BUT NOT LIMITED TO AN ATTORNEY — REGARDING THE CONSEQUENCES OF YOUR DECISION, JUST AS YOU WOULD WHEN MAKING ANY OTHER IMPORTANT BUSINESS OR LIFE DECISION</li>
            </ul>
            <h6 className="mb-2 text-lg font-bold">14. Governing Law</h6>
            <p className="mb-2">Except where prohibited by law, the laws of Colorado, United States of America, without respect to its conflict of laws, rules, shall govern any disputes arising out of or relating to this Agreement, the Service, or your connection with Blind Date.</p>
            <p className="mb-2">Regardless of the foregoing, the Arbitration Agreement in Section 13 above shall be governed by the Federal Arbitration Act.</p>
            <h6 className="mb-2 text-lg font-bold">15. Venue</h6>
            <p className="mb-2">Except for claims that may be properly brought in a small claims court of competent jurisdiction in the county in which you reside or in the state of Colorado, all claims arising out of or relating to this Agreement, the Service, or your relationship with Blind Date that are not submitted to arbitration for whatever reason will be litigated exclusively in the federal or state courts of Colorado, U.S.A. You and Blind Date consent to the exercise of personal jurisdiction of courts in the State of Colorado and waive any claim that such courts constitute an inconvenient forum.</p>
            <h6 className="mb-2 text-lg font-bold">16. Indemnity by You</h6>
            <p className="mb-2">You agree to indemnify, defend, and hold harmless Blind Date, our affiliates, and their and our respective officers, directors, agents, and employees from and against any and all complaints, demands, claims, damages, losses, costs, liabilities, and expenses, including attorney's fees, arising out of, relating to, or resulting from your access to or use of the Blind Date Service, your Content, or your breach of this Agreement, to the extent permitted by applicable law.</p>
            <h6 className="mb-2 text-lg font-bold">17. Entire Agreement; Other</h6>
            <p className="mb-2">This Agreement, together with the Privacy Policy, the Safety Tips, and any terms disclosed to you if you purchase or have purchased additional features, products, or services we offer on the Service, constitute the entire agreement between you and Blind Date regarding your relationship with Blind Date and use of Blind Date, with the following exception: anyone who has opted out of the retroactive implementation of Section 13 is still subject to and within the bounds by any prior agreements to arbitrate with Blind Date as well as this agreement to arbitrate on a going-forward basis.</p>
            <p className="mb-2">If any part of this Agreement is found to be invalid, the remaining provisions of this Agreement will always remain in full force and effect.</p>
            <p className="mb-2">Blind Date's omission to force any right or term of this Agreement shall not be construed as a waiver of such right or provision.</p>
            <p className="mb-2">You agree that your Blind Date account is non-transferable, and that all of your rights to your account and its Content expire when you die.</p>
            <p className="mb-2">This Agreement on this Terms of Use does not create any agency, partnership, joint venture, fiduciary, and or any other special relationship or employment, and you may not make any statements on Blind Date's behalf or bind Blind Date in any way.</p>
        </main>
        
            {/* <h6 className="mb-2 text-lg font-bold"></h6>
            <p className="mb-2"></p>
            <p className="mb-2"></p>
            <p className="mb-2"></p>

            <h6 className="mb-2 text-lg font-bold"></h6>
            <p className="mb-2"></p>
            <ul className="mb-2">
                <li className="mb-2 list-disc ml-10 pl-5"></li>
                <li className="mb-2 list-disc ml-10 pl-5"></li>
                <li className="mb-2 list-disc ml-10 pl-5"></li>
                <li className="mb-2 list-disc ml-10 pl-5"></li>
            </ul>

            <Link className="border-b-2 text-blue-600" to={'/legal/privacy_policy'}></Link>
            <Link className="text-blue-600 border-b-2" to='javascript:void(0)' onClick={() => window.location.href = 'mailto:help@blinddate.world'}>help@blinddate.world</Link> */}
    </div>
  )
}

export default TermsAndConditions
